---
strict: true
site_name: mappers
site_description: |
  Declarative mappers from ORM models to domain entities. And back
  again!
theme:
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  logo: "https://raw.githubusercontent.com\
    /dry-python/brand/master/logo/dry-python.png"
  # FIXME: Favicon.
  language: 'en'
repo_name: mappers
repo_url: 'https://github.com/dry-python/mappers'
edit_uri: ''
extra:
  social:
    - type: github
      link: 'https://github.com/dry-python'
    - type: twitter
      link: 'https://twitter.com/dry_py'
    - type: linkedin
      link: 'https://www.linkedin.com/company/drylabs/'
    # FIXME: Its not `fa` its `fab` class.  Also, reorder when fixed.
    - type: gitter
      link: 'https://gitter.im/dry-python/mappers'
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
